"""Updated project model, added user_background and project_requests

Revision ID: 3a985378a518
Revises: a0a3f5b95338
Create Date: 2025-06-24 07:11:48.761438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a985378a518'
down_revision = 'a0a3f5b95338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_admin'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['user_id'])

    with op.batch_alter_table('user_backgrounds', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_backgrounds_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_backgrounds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_backgrounds_ibfk_1'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_project_admin'), 'users', ['admin_id'], ['user_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
