"""work_type to string

Revision ID: 494d4ee0c469
Revises: 
Create Date: 2025-06-17 06:09:33.668984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '494d4ee0c469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('work_type',
               existing_type=mysql.JSON(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('work_type',
               existing_type=sa.String(length=100),
               type_=mysql.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
